#!/bin/bash

[ "$SKIP_GIT_HOOKS" ] && exit 0

echo "-----> [pre-commit hook] flow"

# echo Running flow
# echo skipped
# exit 0

# exit 0
./node_modules/.bin/flow
if [ $? != 0 ]; then
	# echo -e ""
	exec < /dev/tty

	echo canceled; 
	exit 1;
fi
