#!/bin/bash

#echo "Xcode 10 fix, install third parties"
#if [ ! -d "node_modules/react-native/third-party" ]; then
#  cd node_modules/react-native ; ./scripts/ios-install-third-party.sh ; cd ../../
#  cd node_modules/react-native/third-party/glog-0.3.5/ ; ./configure ; cd ../../../../

#  echo "Hack glog signalhandler https://github.com/facebook/react-native/issues/16106"
#  glog_file=./node_modules/react-native/third-party/glog-0.3.5/src/signalhandler.cc
  #sed -i '' 's/(void\*)context->PC_FROM_UCONTEXT/NULL/g' $glog_file
#  sed -i "" "78s|.*|    return NULL;|" $glog_file
#fi

echo "fix redux-persist flow issue https://github.com/rt2zz/redux-persist/issues/908"
persist_reducer=./node_modules/redux-persist/lib/persistReducer.js.flow
persist_react=./node_modules/redux-persist/lib/integration/react.js.flow
#sed -i '' 's/State: Object, Action: Object/State: any, Action: Object/g' $persist_reducer
sed -i '' 's/children?: Node | Function,/children: Node | Function,/g' $persist_react
sed -i '' 's/loading?: Node,/loading: Node,/g' $persist_react

echo "update sdk version react-native-reanimated"
persist_reducer=./node_modules/react-native-reanimated/android/build.gradle
sed -i '' 's/compileSdkVersion 25/compileSdkVersion 27/g' $persist_reducer
sed -i '' 's/buildToolsVersion "25.0.2"/buildToolsVersion "27.0.3"/g' $persist_reducer
sed -i '' 's/targetSdkVersion 22/targetSdkVersion 26/g' $persist_reducer
