#!/bin/bash


echo "fix react-native-gesture-handler types"
gesture_handler=./node_modules/react-native-gesture-handler/react-native-gesture-handler.d.ts
sed -i '' 's/Animated, StatusBarAnimation/Animated, StatusBarAnimation, ViewStyle, StyleProp/g' $gesture_handler

echo "update sdk version react-native-reanimated"
persist_reducer=./node_modules/react-native-reanimated/android/build.gradle
sed -i '' 's/compileSdkVersion 25/compileSdkVersion 27/g' $persist_reducer
sed -i '' 's/buildToolsVersion "25.0.2"/buildToolsVersion "27.0.3"/g' $persist_reducer
sed -i '' 's/targetSdkVersion 22/targetSdkVersion 26/g' $persist_reducer
